---
- include: ./install_packages.yml

- name: checking that RVM is installed
  sudo: rvm.sudo
  file:
    path: "{{rvm.init_script}}"
    state: file
  ignore_errors: true
  register: rvm_install_result

- include: ./install_rvm.yml
  when: rvm_install_result|failed

- include: ./update_rvm.yml
  when: rvm.auto_update_rvm and rvm_install_result|success

- include: ./select_ruby.yml

- include: ./install_ruby.yml
  when: rvm_select_ruby_version|failed
