---
- name: setting default Ruby version
  become_user: "{{rvm.become_user}}"
  shell: "source {{rvm.init_script}} && rvm use {{rvm.default_ruby_version}} --default executable=/bin/bash"
  register: rvm_select_ruby_version
  ignore_errors: True
  changed_when: False
